### ISSUE TITLE
tagging FreeType

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGraphics/FreeType.jl#7]
Hi, 
would it be possible to tag `FreeType`? 
On `OSX` this is still failing with the current tag!
Thanks a lot!

Simon

**Comment by jhasse** [comment]
Okay I've tried this, but `Pkg.publish()` always fails. I've upgraded Julia to 0.5-dev, but then `Pkg.publish()` gives me

```
ERROR: There are no METADATA changes to publish
```

but `Pkg.tag("FreeType")` returns

```
fatal: Tag 'v1.0.1' existiert bereits
```

(German for tag already exists ...). I guess this is because I already created the Tag in 0.4. Unfortunately there doesn't seem to be an easy way to install Julia 0.4 on Ubuntu atm. Is it okay if I wait a few days?

Also if you like, you can try to create the PR in METADATA.jl manually :)
